name: homebound
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  provider: ^4.3.2+2
  google_nav_bar: ^3.1.0
  line_icons: ^0.2.0
  simple_animations: ^1.3.3
  shared_preferences: any
  flushbar: ^1.10.4
  carousel_slider: ^1.4.1
  photo_view: ^0.10.2
  flutter_swiper: ^1.1.6
  delayed_display: ^1.0.3
  badges: ^1.1.4

  giffy_dialog: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true



  assets:
  - assets/
  - assets/images/

fonts:
    - family: Gilroy
      fonts:
        - asset: assets/Gilroy-Light.otf
        - asset: assets/Gilroy-ExtraBold.otf
